// ============================================================
//  ASPU INSIGHT — Data File
//  استبدل هاد الملف بالـ API لما تكون جاهز
//  Replace with API calls when ready
// ============================================================

// ── Reader People (used in popup) ──────────────────────────
export const apiReaderPeople = {
  doctors: [
    {
      nameAr: "د. خالد منصور",
      nameEn: "Dr. Khalid Mansour",
      roleAr: "أستاذ مساعد — هندسة معلوماتية",
      roleEn: "Asst. Prof. — Informatics Eng.",
      date: "2024-11-02",
    },
    {
      nameAr: "د. ريم سليمان",
      nameEn: "Dr. Reem Suleiman",
      roleAr: "أستاذ — علم البيانات",
      roleEn: "Prof. — Data Science",
      date: "2024-10-28",
    },
    {
      nameAr: "د. سامي الحمدان",
      nameEn: "Dr. Sami Al-Hamdan",
      roleAr: "أستاذ مشارك — شبكات",
      roleEn: "Assoc. Prof. — Networks",
      date: "2024-10-15",
    },
    {
      nameAr: "د. نادية عمر",
      nameEn: "Dr. Nadia Omar",
      roleAr: "أستاذ — أمن المعلومات",
      roleEn: "Prof. — Cybersecurity",
      date: "2024-09-30",
    },
  ],
  students: [
    {
      nameAr: "أحمد سالم",
      nameEn: "Ahmad Salem",
      roleAr: "طالب ماجستير",
      roleEn: "MSc Student — Informatics",
      date: "2024-11-05",
    },
    {
      nameAr: "هلا عمر",
      nameEn: "Hala Omar",
      roleAr: "طالبة بكالوريوس — السنة الرابعة",
      roleEn: "Undergraduate — Year 4",
      date: "2024-11-04",
    },
    {
      nameAr: "عمر الدبس",
      nameEn: "Omar Al-Dabbs",
      roleAr: "طالب بكالوريوس — السنة الثالثة",
      roleEn: "Undergraduate — Year 3",
      date: "2024-11-01",
    },
    {
      nameAr: "ديما الزين",
      nameEn: "Dima Al-Zein",
      roleAr: "طالبة دكتوراه",
      roleEn: "PhD Student",
      date: "2024-10-22",
    },
    {
      nameAr: "باسل القاضي",
      nameEn: "Basel Al-Qadi",
      roleAr: "طالب ماجستير",
      roleEn: "MSc Student",
      date: "2024-10-18",
    },
  ],
  agencies: [
    {
      nameAr: "المعهد العربي للتقنية",
      nameEn: "Arab Technology Institute",
      roleAr: "جهة علمية — سوريا",
      roleEn: "Scientific Agency — Syria",
      date: "2024-10-30",
    },
    {
      nameAr: "مركز أبحاث الذكاء الاصطناعي",
      nameEn: "AI Research Centre",
      roleAr: "مركز بحثي — دمشق",
      roleEn: "Research Centre — Damascus",
      date: "2024-10-20",
    },
  ],
};

// ── Papers List ─────────────────────────────────────────────
export const apiPapers = [
  {
    id: 1,
    titleAr: "نظام تلقائي لكشف التشابه الدلالي في مشاريع التخرج باستخدام نماذج اللغة الكبيرة",
    titleEn: "Automated Semantic Similarity Detection Using Large Language Models",
    excerptAr: "توظيف نماذج BERT العربية لتحليل التشابه الدلالي العميق بين أبحاث الطلبة، مع واجهة تقارير مرئية تفصيلية.",
    excerptEn: "Leveraging Arabic BERT models for deep semantic similarity analysis between student papers with detailed visual reporting.",
    pub: "student",
    type: "scientific",
    disc: "ai",
    authorAr: "سارة الأحمد",
    authorEn: "Sara Al-Ahmad",
    year: 2024,
    rating: 4.9,
    ratingCount: 87,
    readers: 1420,
    readersDoctors: 320,
    readersStudents: 940,
    readersAgency: 160,
  },
  {
    id: 2,
    titleAr: "اكتشاف التهديدات السيبرانية في الوقت الحقيقي باستخدام التعلم العميق",
    titleEn: "Real-Time Cyber Threat Detection Using Deep Learning",
    excerptAr: "نموذج هجين LSTM+Attention لتصنيف حركة الشبكة وكشف الاختراقات بدقة تجاوزت 97%.",
    excerptEn: "Hybrid LSTM+Attention model for network traffic classification with 97%+ accuracy.",
    pub: "student",
    type: "scientific",
    disc: "sec",
    authorAr: "محمد العلي",
    authorEn: "Mohammad Al-Ali",
    year: 2024,
    rating: 4.7,
    ratingCount: 62,
    readers: 1105,
    readersDoctors: 280,
    readersStudents: 720,
    readersAgency: 105,
  },
  {
    id: 3,
    titleAr: "بنية تحتية للحوسبة السحابية الهجينة لتطبيقات الجامعة",
    titleEn: "Hybrid Cloud Infrastructure Architecture for University Applications",
    excerptAr: "تصميم وتنفيذ بنية سحابية هجينة تجمع بين AWS والخوادم المحلية.",
    excerptEn: "Design and implementation of a hybrid cloud architecture combining AWS and on-premise servers.",
    pub: "professor",
    type: "scientific",
    disc: "net",
    authorAr: "د. خالد منصور",
    authorEn: "Dr. Khalid Mansour",
    year: 2024,
    rating: 4.8,
    ratingCount: 45,
    readers: 2180,
    readersDoctors: 890,
    readersStudents: 980,
    readersAgency: 310,
  },
  {
    id: 4,
    titleAr: "تطبيق إدارة مكتبة جامعية مع ميزات الذكاء الاصطناعي",
    titleEn: "University Library Management App with AI Features",
    excerptAr: "تطبيق Flutter متكامل لإدارة موارد المكتبة مع نظام توصية ذكي بالكتب.",
    excerptEn: "Full-stack Flutter app for library resource management with intelligent book recommendation.",
    pub: "student",
    type: "srs",
    disc: "app",
    authorAr: "لمى البكري",
    authorEn: "Lama Al-Bakri",
    year: 2024,
    rating: 4.5,
    ratingCount: 38,
    readers: 674,
    readersDoctors: 120,
    readersStudents: 480,
    readersAgency: 74,
  },
  {
    id: 5,
    titleAr: "تحليل مشاعر التغريدات العربية باستخدام نماذج المحولات",
    titleEn: "Arabic Tweet Sentiment Analysis Using Transformer Models",
    excerptAr: "دراسة مقارنة لـ CAMeLBERT وAraBERT على 50,000 تغريدة سورية باللهجة العامية.",
    excerptEn: "Comparative study of CAMeLBERT vs AraBERT on 50K Syrian dialect tweets.",
    pub: "student",
    type: "master",
    disc: "data",
    authorAr: "نور الحسن",
    authorEn: "Nour Al-Hassan",
    year: 2023,
    rating: 4.6,
    ratingCount: 71,
    readers: 1890,
    readersDoctors: 560,
    readersStudents: 1100,
    readersAgency: 230,
  },
  {
    id: 6,
    titleAr: "تقنيات فيدرالية التعلم الآلي للحفاظ على خصوصية البيانات الصحية",
    titleEn: "Federated Machine Learning for Medical Data Privacy Preservation",
    excerptAr: "تطبيق نماذج التعلم الموزع على البيانات الطبية مع ضمان الخصوصية الكاملة.",
    excerptEn: "Application of federated learning on medical datasets with full privacy guarantees.",
    pub: "professor",
    type: "scientific",
    disc: "ai",
    authorAr: "د. ريم سليمان",
    authorEn: "Dr. Reem Suleiman",
    year: 2024,
    rating: 4.9,
    ratingCount: 93,
    readers: 3240,
    readersDoctors: 1200,
    readersStudents: 1540,
    readersAgency: 500,
  },
  {
    id: 7,
    titleAr: "منصة تعليمية تفاعلية مدعومة بالذكاء الاصطناعي للتعلم التكيّفي",
    titleEn: "AI-Powered E-Learning Platform for Adaptive Learning",
    excerptAr: "نظام LMS يكيّف المسارات التعليمية تلقائياً بناءً على سلوك الطالب.",
    excerptEn: "Full LMS with automatic curriculum adaptation based on student behavior.",
    pub: "student",
    type: "srs",
    disc: "app",
    authorAr: "أحمد سالم",
    authorEn: "Ahmad Salem",
    year: 2024,
    rating: 4.4,
    ratingCount: 29,
    readers: 512,
    readersDoctors: 90,
    readersStudents: 380,
    readersAgency: 42,
  },
  {
    id: 8,
    titleAr: "خوارزميات تحسين توزيع الطيف الديناميكي في شبكات 5G",
    titleEn: "Dynamic Spectrum Allocation Optimisation for Dense 5G Networks",
    excerptAr: "رسالة دكتوراه — خوارزميتان جديدتان مع تحسين 34% في كفاءة الشبكة.",
    excerptEn: "PhD — Two novel adaptive algorithms achieving 34% network efficiency gain.",
    pub: "student",
    type: "phd",
    disc: "net",
    authorAr: "باسل القاضي",
    authorEn: "Basel Al-Qadi",
    year: 2023,
    rating: 4.8,
    ratingCount: 54,
    readers: 2760,
    readersDoctors: 1040,
    readersStudents: 1380,
    readersAgency: 340,
  },
  {
    id: 9,
    titleAr: "نظام لتحليل صور الرنين المغناطيسي لاكتشاف أورام الدماغ",
    titleEn: "Deep Learning MRI Analysis System for Brain Tumour Detection",
    excerptAr: "نموذج CNN يحقق دقة 98.3% في تصنيف أورام الدماغ من صور MRI.",
    excerptEn: "CNN model achieving 98.3% accuracy in brain tumour classification from MRI.",
    pub: "student",
    type: "master",
    disc: "ai",
    authorAr: "هلا عمر",
    authorEn: "Hala Omar",
    year: 2024,
    rating: 4.9,
    ratingCount: 108,
    readers: 4120,
    readersDoctors: 1800,
    readersStudents: 1920,
    readersAgency: 400,
  },
  {
    id: 10,
    titleAr: "أمن تطبيقات الويب: كشف ثغرات OWASP Top 10 تلقائياً",
    titleEn: "Web Application Security: Automated OWASP Top 10 Vulnerability Detection",
    excerptAr: "أداة مفتوحة المصدر لمسح تطبيقات الويب ورصد نقاط ضعف OWASP.",
    excerptEn: "Open-source scanner detecting OWASP top vulnerabilities with detailed reports.",
    pub: "student",
    type: "srs",
    disc: "sec",
    authorAr: "عمر الدبس",
    authorEn: "Omar Al-Dabbs",
    year: 2024,
    rating: 4.3,
    ratingCount: 41,
    readers: 688,
    readersDoctors: 180,
    readersStudents: 420,
    readersAgency: 88,
  },
  {
    id: 11,
    titleAr: "معمارية الحوسبة بالحافة للتطبيقات الصناعية الذكية",
    titleEn: "Edge Computing Architecture for Smart Industrial Applications",
    excerptAr: "بحث في تصميم بنى معمارية للحوسبة بالحافة لتطبيقات الصناعة 4.0.",
    excerptEn: "Technical research on edge computing architectures supporting Industry 4.0.",
    pub: "professor",
    type: "scientific",
    disc: "net",
    authorAr: "د. سامي الحمدان",
    authorEn: "Dr. Sami Al-Hamdan",
    year: 2024,
    rating: 4.6,
    ratingCount: 37,
    readers: 1650,
    readersDoctors: 720,
    readersStudents: 730,
    readersAgency: 200,
  },
  {
    id: 12,
    titleAr: "نظام توصية هجين للتجارة الإلكترونية",
    titleEn: "Hybrid Recommendation System for E-commerce",
    excerptAr: "نموذج يجمع التصفية التعاونية وتحليل المحتوى مع تقنيات NLP.",
    excerptEn: "Hybrid model combining collaborative filtering and NLP-based content analysis.",
    pub: "student",
    type: "scientific",
    disc: "data",
    authorAr: "ديما الزين",
    authorEn: "Dima Al-Zein",
    year: 2023,
    rating: 4.5,
    ratingCount: 56,
    readers: 980,
    readersDoctors: 240,
    readersStudents: 620,
    readersAgency: 120,
  },
];

// ── Lookup Maps ──────────────────────────────────────────────
export const apiTypeMeta = {
  scientific: { ar: "بحث علمي تقني", en: "Scientific Research", cls: "tb-student-sci" },
  srs:        { ar: "مشروع SRS",      en: "SRS Project",         cls: "tb-student-srs" },
  master:     { ar: "رسالة ماجستير",  en: "Master's Thesis",     cls: "tb-student-master" },
  phd:        { ar: "رسالة دكتوراه",  en: "PhD Dissertation",    cls: "tb-student-phd" },
};

export const apiPubMeta = {
  student:   { ar: "طالب",          en: "Student",   dotCls: "ab-student" },
  professor: { ar: "أستاذ",         en: "Professor", dotCls: "ab-prof" },
};

// ── Page-level stats (header) ────────────────────────────────
export const apiPageStats = {
  totalPublished:  "1,240",
  totalReads:      "48,320",
  avgRating:       "4.3",
  disciplines:     "8",
};

// ── Filter sidebar counts ────────────────────────────────────
export const apiFilterCounts = {
  pub:  { student: 986, professor: 254 },
  type: { scientific: 542, srs: 318, master: 248, phd: 132 },
  disc: { ai: 234, sec: 187, app: 156, data: 128, net: 98, se: 112 },
};